import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Body from '../components/body'
import Achievements from '../components/achievements'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Purdue Dota 2 Club</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Body />
      <Achievements />
    </div>
  )
}
